### ISSUE TITLE
Update the Pipelines UI

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-runtime-console#254]
Please update the UI to match the wireframes.

https://redhat.invisionapp.com/share/3UAZNL1JQ#/screens/224946838

**Comment by rawlingsj** [comment]
@pmuir @catrobson @jstrachan do these designs cater for CI verses CD pipelines or are both on the same screen?  I think that may get busy and it would be a nicer experience if you can just view the pull request or release pipelines.

FWIW on the next jenkins release builds will have an annotation on them to identify if the build is CI or CD.

```
apiVersion: v1
kind: Build
metadata:
  annotations:
    fabric8.io/pipeline.type: cd
```
